### ISSUE TITLE
Re-add license field to Cargo.toml

### ISSUE THREAD

**Issue by sdroege** [hsivonen/encoding_rs#75]
This was removed in https://github.com/hsivonen/encoding_rs/commit/3a4033e67b6b9d1c1e9514bcb5c20ae05bf8391d#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542 and causes automated tooling like `cargo deny` to fail detecting the license.

It should probably be something like `(Apache-2.0 OR MIT) AND BSD-3` but I'm not sure the expression syntax allows parenthesis. If it doesn't then we have a problem and you might want to reconsider if dual-licensing warrants the increased license complexity here. Having to worry about 3 different licenses for a single crate is a bit suboptimal, even if MIT and BSD-3 are approximately the same.

**Comment by sdroege** [comment]
`cargo deny` is accepting the following fwiw:

```toml
[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]
```
